### ISSUE TITLE
Image parsing spams output to System.err

### ISSUE THREAD

**Issue by lapo-luchini** [AdoptOpenJDK/openjdk-jdk11u#21]
I would suggest changing those `e.printStackTrace()` (which can easily happen e.g. if the users uploads an image with an unsupported color space) to proper calls to `java.util.logging` so that they can properly filtered and/or printed to a specific separate log.

https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/fa3ecefdd6eb14a910ae75b7c0aefb1cf8eedcce/src/java.desktop/share/classes/sun/awt/image/InputStreamImageSource.java#L274

In stderr I currently receive a lot of these:

```
sun.awt.image.ImageFormatException: Unsupported color conversion request
	at sun.awt.image.JPEGImageDecoder.readImage(Native Method)
	at sun.awt.image.JPEGImageDecoder.produceImage(JPEGImageDecoder.java:141)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)
sun.awt.image.ImageFormatException: Unsupported color conversion request
	at sun.awt.image.JPEGImageDecoder.readImage(Native Method)
	at sun.awt.image.JPEGImageDecoder.produceImage(JPEGImageDecoder.java:141)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)
```

**Comment by lapo-luchini** [comment]
BTW: it is the same in [OpenJDK 8](https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/sun/awt/image/InputStreamImageSource.java#L274) and [OpenJDK 15](https://github.com/AdoptOpenJDK/openjdk-jdk15u/blob/master/src/java.desktop/share/classes/sun/awt/image/InputStreamImageSource.java#L271) too.

**Comment by karianna** [comment]
These suggestions should be made at openjdk.java.net (core-libs-dev mailing list)

**Comment by lapo-luchini** [comment]
PS: anybody interested can follow [JDK-8265603](https://bugs.openjdk.java.net/browse/JDK-8265603).
